language: ruby
rvm: 2.4.1
cache: bundler
script: bundle exec rake test
addons:
  postgresql: "9.6"
before_script:
  - sudo apt-get install postgresql-server-dev-9.6
  - wget https://github.com/dalibo/hypopg/archive/1.0.0.tar.gz
  - tar xf 1.0.0.tar.gz
  - cd hypopg-1.0.0
  - make
  - sudo make install
  - psql -c 'create database dexter_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
